export enum Configuration{
    PORT = "PORT",
    HOST= "HOST", 
    USERNAME = "USERNAME",
    PASSWORD = "PASSWORD",   
    DATABASE = "DATABASE",
    PORTDATABASE="PORTDATABASE",
    JWT_SECRET="JWT_SECRET"
}